version: "3.8"
services:
  postgres_store1:
    image: postgres:15
    container_name: postgres_store1
    environment:
      POSTGRES_DB: sales_database
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
    ports:
      - "5434:5432"
    volumes:
      - ./sales_data.sql:/docker-entrypoint-initdb.d/init.sql

  postgres_store2:
    image: postgres:15
    container_name: postgres_store2
    environment:
      POSTGRES_DB: sales_2_database
      POSTGRES_USER: user2
      POSTGRES_PASSWORD: password2
    ports:
      - "5435:5432"
    volumes:
      - ./sales_2_data.sql:/docker-entrypoint-initdb.d/init.sql
